name = "offchain-sales-boilerplate-test"
pages_build_output_dir = "./dist"

kv_namespaces = [
    { binding = "season_pass", id = "8acf8b389c4349a8a726d87f6723cb69" }
]

[vars]
PROJECT_ACCESS_KEY = "AQAAAAAAADVH8R2AGuQhwQ1y8NaEf1T7PJM"

[dev]
port = 4444
